#############################################################################
# Makefile for building: UDPtest
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Aug 26 10:55:36 2015
# Project:  UDPtest.pro
# Template: app
# Command: /home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile UDPtest.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -I. -I../Desktop/Qt/4.8.1/gcc/include/QtCore -I../Desktop/Qt/4.8.1/gcc/include/QtGui -I../Desktop/Qt/4.8.1/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtGui -L/home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.cpp \
		main.cpp \
		Udptrans.cpp moc_mainwindow.cpp
OBJECTS       = mainwindow.o \
		main.o \
		Udptrans.o \
		moc_mainwindow.o
DIST          = ../Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		UDPtest.pro
QMAKE_TARGET  = UDPtest
DESTDIR       = 
TARGET        = UDPtest

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: UDPtest.pro  ../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++/qmake.conf ../Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl \
		/home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl
	$(QMAKE) -spec ../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile UDPtest.pro
../Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl:
/home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile UDPtest.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/UDPtest1.0.0 || $(MKDIR) .tmp/UDPtest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/UDPtest1.0.0/ && $(COPY_FILE) --parents mainwindow.h Udptrans.h .tmp/UDPtest1.0.0/ && $(COPY_FILE) --parents mainwindow.cpp main.cpp Udptrans.cpp .tmp/UDPtest1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/UDPtest1.0.0/ && (cd `dirname .tmp/UDPtest1.0.0` && $(TAR) UDPtest1.0.0.tar UDPtest1.0.0 && $(COMPRESS) UDPtest1.0.0.tar) && $(MOVE) `dirname .tmp/UDPtest1.0.0`/UDPtest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/UDPtest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/fanwise/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

main.o: main.cpp mainwindow.h \
		Udptrans.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Udptrans.o: Udptrans.cpp Udptrans.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Udptrans.o Udptrans.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

